---
title: "Contact Us"
date: last-modified
---

## Before the class begins on 2026-08-25

If you have any questions before class begins, email Professor Love at `thomas dot love at case dot edu`.

## Once the class begins

If you’ve spent 15 minutes working on something and are stuck, don’t keep working on it. ASK FOR HELP. To get help in this course, you have three main options...

1. Ask a Teaching Assistant (TA) for help during their office hours, or 
2. send an email to `431-help@case.edu` and we'll respond quickly, or
3. ask Professor Love for help before or after class.

- Professor Love is usually available in our classroom 10 minutes before and for some time after each class on Tuesdays and Thursdays. Should you want to make an appointment with him for a longer or more personal conversation, just email him at **Thomas** dot **Love** at **case** dot **edu**.
- [This section](https://thomaselove.github.io/431-syllabus-2026/09_gettinghelp.html) of our Syllabus provides additional information on getting help, including descriptions of how we use [Canvas](https://canvas.case.edu/) and [Google Drive](google.qmd).

## Other Things

We cannot emphasize enough how much we want to hear from you about things that are relevant to this course. 

- Email us at `431-help@case.edu` with your corrections to typos, suggestions, comments and other things. See the syllabus' description of [bonus points](https://thomaselove.github.io/431-syllabus-2026/11_grading.html#bonus-points) for some additional ideas.
- Email Professor Love directly if you want to discuss something that you don't feel comfortable discussing with a TA.

## TA Office Hours

TA Office Hours for 431 will begin on Sunday 2026-08-30 and continue through Tuesday 2026-12-08. 

- All TA Office Hours are held over Zoom. 
- Our [Shared Google Drive (431 Fall 2026 Dr Love and Students)](google.qmd) will display Zoom links for all TA office hours in a document called **431 TA office hours schedule and Zoom links**. 
- No appointment is necessary. Please just drop in.

DATE | TIME(S) (All times Eastern)
:--------: | :----------------------------------
Sundays | 1:00 - 2:00 PM, 5:30 - 8:30 PM
Mondays | 2:00 - 5:00 PM, 5:30 - 7:30 PM, 8:00 - 9:00 PM
Tuesdays | 5:30 - 7:30 PM, 9:00 - 10:00 PM
Wednesdays | none
Thursdays | 10:00 AM - Noon
Fridays | 10:00 AM - Noon, 12:30 - 2:30 PM, 3:00 - 5:00 PM
Saturdays | 10:00 AM - Noon, 6:00 - 8:00 PM

- 431 TA Office Hours are **cancelled** on Monday 2026-10-19 and Tuesday 2026–10-20 for Fall Break, and also **cancelled** from Saturday 2026-11-21 through Friday 2026-11-27 during Thanksgiving Week.

The [Syllabus](https://thomaselove.github.io/431-syllabus-2025/08_teachingassistants.html) provides information on each of this semester's TAs. 

