---
title: "431 Course Main Page: Fall 2026"
author: "Thomas E. Love"
date: last-modified
---

# Welcome! 

431 is the first course of a two-semester sequence (with 432) on applied statistics and data science taught by Professor Thomas E. Love in the [Department of Population and Quantitative Health Sciences](https://case.edu/medicine/pqhs/) at [Case Western Reserve University](https://case.edu/).

## Getting Started

Your first few steps in this course are to:

1. Register and enroll via the [CWRU Student Information System (SIS)](https://sis.case.edu/).
    - Most students^[MPH students should register for MPHP 431, while CRSP and CTS students should register for CRSP 431.] should register for PQHS 431. Dr. Love teaches Section 100.
2. Visit [this link](https://case.edu/registrar/general/sis-resources/record-your-name-pronunciation) to record a pronunciation of your full name in the Student Information System so all of your instructors (and fellow students) can hear it.
3. Complete the [Welcome to 431 survey form](https://tinyurl.com/431-2026-welcome), which is your first assignment^[The survey is due at noon on Wednesday 2026-08-26, but please complete it as soon as you can.].
    - Note: You must log into Google **via CWRU** in order to access the Survey.
4. Obtain David Spiegelhalter's book [The Art of Statistics: How to Learn from Data](https://www.amazon.com/Art-Statistics-How-Learn-Data/dp/1541675703), originally published in 2020 and available at all major retailers for less than \$20.
5. Visit our [Software page](software.qmd) to start the process of installing all necessary software. 

## Everything will appear on this website

Materials you will find include:

-   the course [syllabus](https://thomaselove.github.io/431-syllabus-2026/),
-   the course [calendar](calendar.qmd), which is the final word on all deadlines, and also links to materials for each class session,
-   Professor Love's [431 book](https://thomaselove.github.io/431-book/) entitled "Applied Statistics and R Foundations for 431",
-   detailed information on all course [assignments](assignments.qmd), 
-   information on [software](software.qmd), including installation instructions for R, RStudio, and the key R packages and data sets we'll use,
-   suggested [resources](resources.qmd) to aid in your learning, and
-   information on how to [contact us](contact.qmd).

## Class Starts Tuesday 2026-08-25 at 1 PM

Class will be held on Tuesdays and Thursdays from 1:00 - 2:15 PM in Room E321-E323 at CWRU's School of Medicine, starting on 2026-08-25. In-person attendance is expected.

## Questions?

If you have any questions, contact Professor Love at `thomas dot love at case dot edu`.

Thank you.


